version: '3'

services:

  php-apache:
    build:
      ./php # используем докерфайл, так как должны подкачать mysqli
    ports:
      - 80:80 # первый порт - наша машина, второй порт - виртуальная
    volumes:
      - ./src:/var/www/html # линукуем папку с index.php и style.css с папкой в виртуальной машине
    depends_on:
      - mysql # запустится после базы

  mysql:
    image: mysql # образ mysql 
    container_name: DB # ставим имя контейнеру, чтобы в mysqli обратиться к нему
    volumes: 
      - "./sql/init.sql:/docker-entrypoint-initdb.d/1.sql" # линкуем файл инициализации бд к файлу запуска
    environment:
      MYSQL_ROOT_PASSWORD: password # пароль нужно поставить, иначе заругает mysql

  drawer:
    container_name: Drawer
    image: php:7.2-apache
    ports:
      - 1001:80
    volumes:
      - ./drawer:/var/www/html
    

  sorter:
    container_name: Sorter
    image: php:7.2-apache
    ports:
      - 1002:80
    volumes:
      - ./sorter:/var/www/html

  consoler:
    container_name: Consoler
    image: php:7.2-apache
    ports:
      - 1003:80
    volumes:
      - ./consoler:/var/www/html